#!/bin/sh
set -e
. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

FLEXGET_CONF="/etc/flexget/config.yml"
OMV_FLEXGET_CONF="/home/flexget/.flexget/config.yml"

cp -f ${FLEXGET_CONF} ${OMV_FLEXGET_CONF}

exit 0
