#!/bin/sh
set -e
. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions
OMV_FLEXGET_XPATH="/config/services/flexget"
OMV_FLEXGET_CONF="/etc/flexget/config.yml"
#cat <<EOF > ${OMV_FLEXGET_CONF}
#$(omv_config_get "${OMV_FLEXGET_XPATH}/config")
#EOF

xmlstarlet sel -t \
  -v "//services/flexget/config" -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_FLEXGET_CONF}

exit 0
