schedules:
  - tasks: '*'
    interval:
      hours: 2

templates:
  global:
    email:
      from: 123@gmail.com
      to:
        - 123@gmail.com
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_username: 123@gmail.com
      smtp_password: zdfsdsgfdg
      smtp_tls: true
      template: poster
    deluge:
      port: 58846
      username: admin
      password: torrent
      ratio: 1.1
      removeatratio: yes

  tv:
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
        - '*.avi'
        - '*.rar'
        - '*.MP4'
      reject:
        - '*.zip'
        - '*.wmv'
    regexp:
      reject_excluding:
        - (KILLER|DIMENSION|IMMERSE|REMARKABLE|EVOLVE|TLA|FoV|2HD|RiVER|FTP|YFN|WiKi|BAFT|BAJSKORV|Japhson|BATV|For.Flexget|SM|FaiLED)
      reject:
        - ^((((19|20)(([02468][048])|([13579][26]))-02-29))|((20[0-9][0-9])|(19[0-9][0-9]))-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))$
        - 'www.Cpasbien.me'
        - 'DutchReleaseTeam'
        - 'SNEAK.PEAK'
        - 'shadoe'
        - 'promo'
    series:
      - Low Winter Sun:
          quality: 720p
      - Under the Dome:
          quality: 720p
      - The Bridge:
          quality: 720p
      - Ray Donovan:
          quality: 720p
      - Da Vincis Demons:
          quality: 720p
      - Nikita:
          begin: S03E17
      - Elementary:
          quality: 720p
      - Homeland:
          begin: S01E12
      - Two and a Half Men:
          quality: 720p
          begin: S09E24
      - The Big Bang Theory:
          quality: 720p
          begin: S05E24
      - The Mentalist:
          quality: 720p
          begin: S04E24
      - The Walking Dead:
          quality: 720p
      - Falling Skies:
          quality: 720p
      - Episodes:
          quality: 720p
          begin: S03E01
      - Anger Management:
          begin: S01E02
      - Breaking Bad:
          quality: 720p
          begin: S04E13
      - Dont Trust the Bitch in Apartment 23:
          begin: S01E07
      - New Girl:
          begin: S01E24
      - Ripper Street:
          quality: 720p
      - Happy Endings
      - The Following:
          quality: 720p
      - House of Cards:
          quality: 720p
      - The Americans:
          quality: 720p
      - Hannibal:
          quality: 720p
      - Come Fly With Me:
          begin: S02E01
      - Profugos:
          begin: S02E01
      - Top Gear:
          quality: 720p
      - Touch:
          quality: 720p
      - Utopia:
          quality: 720p
      - The Fall:
          begin: S02E01
          quality: 720p
      - The Newsroom:
          begin: S02E01
          quality: 720p
      - Hostages:
          quality: 720p
      - The Michael J Fox Show:
          quality: 720p
      - Los 80:
          begin: S06E01
      - Mob City:
          quality: 720p
      - The Great Train Robbery:
          quality: 720p
      - True Detective:
          quality: 720p
      - Broadchurch:
          quality: 720p
          begin: S02E01
      - Sherlock:
          begin: S03E01
      - Helix:
          quality: 720p
      - Silicon Valley:
          quality: 720p
      - Believe:
          quality: 720p
      - Prey:
          quality: 720p
      - From There to Here:
          quality: 720p
      - Game of Thrones:
          quality: 720p
          begin: S04E01
      - 24:
          quality: 720p
          begin: S09E05
      - Line of Duty:
          quality: 720p
          begin: S03E01
      - Halt and Catch Fire:
          quality: 720p
      - Last Week Tonight with John Oliver:
          begin: S01E07
      - Legends:
          quality: 720p
      - Married:
          begin: S01E01
      - Extant:
          begin: S01E03
      - Gotham:
          quality: 720p
          begin: S01E02
    exists_series: /media/63539cb9-1f77-4590-ba39-5919f7b9169b/rar_videos/series
    set:
      path: /media/63539cb9-1f77-4590-ba39-5919f7b9169b/torrent/downloads/
      movedone: /media/63539cb9-1f77-4590-ba39-5919f7b9169b/videos/series/{{series_name}}/Season {{series_season}}/
      label: tv
    download: yes

  movies:
    regexp:
      reject_excluding:
        - (SPARKS|DiVERSiTY|AMIABLE|GECKOS|ALLiANCE|COCAIN|FiCO|YIFY|EVO|iMMORTALs|PHD|PublicHD|LiMiTED|mSD|WiKi|Japhson|SADPANDA|MAJESTIC)
      reject:
        - '[\W_]CAM[\W_]'
        - '[\W_]TS[\W_]'
        - WEBSCR
        - '[\W_]R3[\W_]'
        - DUTCH
        - '[\W_]NL[\W_]'
        - R6
        - spanish
        - Spanish
        - SWESUB
        - '.TPB'
        - R1
        - FRENCH
        - 'Russian Audio'
        - 'WEB-DL'
        - 'WEB DL'
        - '[Eng]BlueLady.mp4'
        - FeCKTaRDS
        - iT@_CREW
        - BINGOWINGZ-UKB-RG
        - GlowGaze.Com
        - WEBRip
        - HDRip
        - 3D
    imdb:
      min_score: 7.0
      min_votes: 10000
      min_year: 2012
      accept_languages:
        - english
        - spanish
        - french
        - portuguese
      reject_languages:
        - hindi
    if:
      - imdb_score > 6.1:
          quality: dvdrip+
      - imdb_score > 7.0:
          quality: bluray+ 720p+
      - documentary in genre:
          set:
            path: /media/63539cb9-1f77-4590-ba39-5919f7b9169b/torrent/downloads/
            movedone: /media/63539cb9-1f77-4590-ba39-5919f7b9169b/videos/documentary/

    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
        - '*.avi'
        - '*.rar'
      reject:
        - '*.zip'
        - '*.wmv'
    exists_movie: /media/63539cb9-1f77-4590-ba39-5919f7b9169b/videos/peliculas/
    set:
      path: /media/63539cb9-1f77-4590-ba39-5919f7b9169b/torrent/downloads/
      movedone: /media/63539cb9-1f77-4590-ba39-5919f7b9169b/videos/peliculas/
      label: movies
    download: true

tasks:
  seed_watchlist:
    priority: 3
    template: no_global
    imdb_list:
      user_id: ur1111111
      list: watchlist
    movie_queue: add
    accept_all: yes
    seen: local

  torlock_movies:
    priority: 92
    rss: http://www.torlock.com/movies/rss.xml
    imdb_lookup: yes
    seen_movies: strict
    movie_queue: accept
    torrent_alive: yes
    template:
      - movies

  speed_cd:
    priority: 8
    rss: http://speed.cd/
    imdb_lookup: yes
    seen_movies: strict
    movie_queue: accept
    torrent_alive: yes
    template:
      - movies

  eztv:
    priority: 70
    rss: http://rss.bt-chat.com/
    template:
      - tv

  speedcdtv:
    priority: 10
    rss: "http://speed.cd/"
    template:
      - tv

  torlock_tv:
    priority: 90
    rss: http://www.torlock.com/television/rss.xml
    template:
      - tv

